### ISSUE TITLE
vue ui error after upgrade to 4.2.0

### ISSUE THREAD

**Issue by GWigWam** [vuejs/vue-cli#5158]
### Version
4.2.0

### Environment info
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Upgrade to v4.2.0:

`npm i -g @vue/cli`

Try to start UI

`vue ui`

### What is expected?
I expect vue ui to start

### What is actually happening?
An error is thrown:

```
module.js:549
    throw err;
    ^

Error: Cannot find module './graphql-server'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\w.ghantous\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\server.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

---
Vue UI did work before I upgraded to 4.2.0, if you require any more info be sure to ask.

**Comment by sopilkar** [comment]
The same problem.
OS: MacOS 10.15.3
Node: 8.16.2
Npm: 6.13.2

**Comment by Glandos** [comment]
I tried `yarn global install graphql-server` but this does not work either. It seems that package was split into multiple small packages, and then renamed to `apollo-server-{BACKEND}`

**Comment by sodatea** [comment]
Fixed in 4.2.1. That file was missing from the npm `files` fields. Sorry for the inconvenience.

**Comment by GWigWam** [comment]
Hi @sodatea, `vue ui` now starts for me, however when I open the page (`localhost:8000`) it's stuck loading.

Tried this in both Firefox and Chrome.

**Comment by LShadal** [comment]
> Hi @sodatea, `vue ui` now starts for me, however when I open the page (`localhost:8000`) it's stuck loading.
> 
> Tried this in both Firefox and Chrome.

Hi, 
Same issue here, stuck at loading. Tried uninstall and reinstall and still the same 😢

**Comment by sodatea** [comment]
Fixed in 4.2.2
😢The bug is due to a wrong RegExp in a file that wasn't covered in the integration tests. We do need to set up a better testing pipeline.

**Comment by GWigWam** [comment]
> 
> 
> Fixed in 4.2.2

Issue has indeed been resolved, thanks for your efforts @sodatea !

**Comment by LShadal** [comment]
Thanks 😄
