### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vue-cli#6373]
### Version
4.5.12

### Environment info
```
Environment Info:

  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.6.0 - /usr/local/bin/npm
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.2 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.11 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli: ^4.5.11 => 4.5.11 
    @vue/cli-overlay:  4.5.11 
    @vue/cli-plugin-babel: ^4.5.11 => 4.5.11 
    @vue/cli-plugin-eslint: ^4.5.11 => 4.5.11 
    @vue/cli-plugin-router:  4.5.11 
    @vue/cli-plugin-unit-jest: ^4.5.11 => 4.5.12 
    @vue/cli-plugin-vuex:  4.5.11 
    @vue/cli-service: ^4.5.11 => 4.5.11 
    @vue/cli-shared-utils:  4.5.12 
    @vue/cli-ui:  4.5.11 
    @vue/cli-ui-addon-webpack:  4.5.11 
    @vue/cli-ui-addon-widgets:  4.5.11 
    @vue/compiler-core:  3.0.5 
    @vue/compiler-dom:  3.0.5 
    @vue/compiler-sfc:  3.0.5 
    @vue/compiler-ssr:  3.0.5 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/eslint-config-standard: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.5 
    @vue/runtime-core:  3.0.5 
    @vue/runtime-dom:  3.0.5 
    @vue/shared:  3.0.5 
    @vue/test-utils: ^1.1.3 => 1.1.3 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^7.8.0 => 7.8.0 
    jest-serializer-vue:  2.0.2 
    typescript:  3.9.7 
    vue: ^2.6.12 => 2.6.12 (3.0.5)
    vue-cli-plugin-apollo:  0.21.3 
    vue-codemod:  0.0.4 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.7 
    vue-loader:  15.9.6 (16.1.2)
    vue-meta: ^2.4.0 => 2.4.0 
    vue-router: ^3.5.1 => 3.5.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.12 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.2 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
When I update from 4.5.11 to 4.5.12, there is a conflict with my site csp: 

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'
```

### What is expected?
No unsafe-eval in the source code 

### What is actually happening?
unsafe-eval conflict with the CSP of my site.

**Comment by sodatea** [comment]
I don't think it's caused by the 4.5.12 update. Please provide a reproduction.

**Comment by francoisromain** [comment]
Your probably right it is not related to vue-cli. 
I can not make a proper repro. 

On this repo: https://github.com/francoisromain/camino-ui

You can: 
- rename `.env-example` as `.env`
- `npm i && npm run build && npm run start`

This works in the browser.

* * *

Now, there is the problem when either: 
- we remove package.lock.json and re-install
- we update vue-cli from 4.5.11 to 4.5.12

Do you have an idea what is the problem? 

Thank you

**Comment by sodatea** [comment]
I don't know. The project is too big that I can't isolate the issues.
By the way, why is `@vue/cli` itself a dependency of the project? I don't see any reference to it. It seems extraneous.

**Comment by francoisromain** [comment]
Yes you are right again: @vue/cli is probably extraneous. 

However if I remove it I have errors in the CI, tests are not running because of `/src/store/__mocks__/setupJest.js: Cannot find module 'core-js/package.json'`

And I still can not isolate the 'unsafe-eval' issue…

**Comment by darrinmn9** [comment]
I think the issue is with webpack.

https://github.com/webpack/webpack/issues/5627#issuecomment-394309966
https://stackoverflow.com/questions/64159951/vue-js-3-extension-breaks-while-using-vue-cli-service-build-due-to-unsafe-eval
