### ISSUE TITLE
@vue/cli-plugin-e2e-webdriverio errors on default template in TS 4.3 and earlier and starts hallucinating on TS 4.4

### ISSUE THREAD

**Issue by HoldYourWaffle** [vuejs/vue-cli#6760]
### Version
4.5.14

### Reproduction link
[github.com](https://github.com/HoldYourWaffle2/vue-ts4.4-e2e-test)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 1500X Quad-Core Processor
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.50)
  npmPackages:
    @vue/cli-overlay:  4.5.14
    @vue/cli-plugin-e2e-webdriverio: ~4.5.0 => 4.5.14
    @vue/cli-plugin-router:  4.5.14
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.14
    @vue/cli-plugin-vuex:  4.5.14
    @vue/cli-service: ~4.5.0 => 4.5.14
    @vue/cli-shared-utils:  4.5.14
    @vue/compiler-core:  3.2.20
    @vue/compiler-dom:  3.2.20
    @vue/compiler-sfc: ^3.0.0 => 3.2.20
    @vue/compiler-ssr:  3.2.20
    @vue/component-compiler-utils:  3.2.2
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.2.20
    @vue/ref-transform:  3.2.20
    @vue/runtime-core:  3.2.20
    @vue/runtime-dom:  3.2.20
    @vue/server-renderer:  3.2.20
    @vue/shared:  3.2.20
    @vue/web-component-wrapper:  1.3.0
    typescript: ~4.1.5 => 4.1.6
    vue: ^3.0.0 => 3.2.20
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.1)
    vue-style-loader:  4.1.3
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. `git clone https://github.com/HoldYourWaffle2/vue-ts4.4-e2e-test` (or `vue create` with WebdriverIO)

2. `npm run test:e2e`
3. Notice these errors:
```
tests/e2e/pageobjects/app.page.ts(17,36): error TS7006: Parameter 'path' implicitly has an 'any' type.
tests/e2e/pageobjects/app.page.ts(23,19): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
```
4. Cry.

5. `git checkout ts4.4` (or `npm install typescript@latest`)
6. `npm run test:e2e`
7. Notice these errors:
```
tests/e2e/specs/app.spec.ts(4,19): error TS2695: Left side of comma operator is unused and has no side effects.
```
8. Cry even more.

9. `git checkout ts-node-update` (or `npm install ts-node@latest`)
10. Observe no changes.
11. Cry and give up.

### What is expected?
A smooth experience when setting up a Vue project with WebdriverIO, preferably also when updating Typescript to 4.4.

### What is actually happening?
The aforementioned errors and crying

---
The error on TS 4.4 is incredibly strange. Its location corresponds to the middle of a string and doesn't change when the source file is modified. However, it disappears when `App` is no longer referenced (apart from the import).
This error doesn't happen on TS 4.3.

Side-note: `vue info` seems to not detect my Chrome and `@vue/cli` installation, but I solemnly swear that I do in fact have those.
