### ISSUE TITLE
Dynamic imports does not work

### ISSUE THREAD

**Issue by efureev** [vuejs/vue-cli#5960]
### Version
4.5.7

### Environment info
```
 System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Firefox: Not Found
    Safari: 14.0
  npmPackages:
    @ascendancyy/vue-cli-plugin-stylelint: ^1.1.2 => 1.1.2 
    @egoist/vue-emotion:  0.6.2 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.7 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.7 
    @vue/cli-plugin-babel: ^4.5.7 => 4.5.7 
    @vue/cli-plugin-eslint: ^4.5.7 => 4.5.7 
    @vue/cli-plugin-router:  4.5.7 
    @vue/cli-plugin-vuex:  4.5.7 
    @vue/cli-service: ^4.5.7 => 4.5.7 
    @vue/cli-shared-utils:  4.5.7 
    @vue/component-compiler-utils:  3.2.0 (3.1.2)
    @vue/eslint-config-airbnb: ^5.0.2 => 5.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    @wtfcode/vue-merge: 1.1.2 => 1.1.2 (2.1.1)
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    portal-vue: ^2.1.7 => 2.1.7 
    svg-to-vue:  0.7.0 
    typescript:  3.8.3 
    vue: ^2.6.12 => 2.6.12 
    vue-async-computed: ^3.8.2 => 3.8.2 
    vue-awesome:  4.1.0 
    vue-class-component:  7.2.5 
    vue-eslint-parser:  7.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.18.2 => 8.18.2 
    vue-json-pretty: ^1.6.5 => 1.6.5 
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-multiselect:  2.1.6 
    vue-property-decorator:  8.5.1 
    vue-rate-it:  2.1.0 
    vue-resize:  0.4.5 
    vue-router: ^3.4.6 => 3.4.6 
    vue-scrollto:  2.18.2 
    vue-select:  3.10.8 
    vue-style-loader:  4.1.2 
    vue-svg-loader: ^0.16.0 => 0.16.0 
    vue-template-compiler: ^2.6.12 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vue-the-mask:  0.11.1 
    vue-toasted: ^1.1.28 => 1.1.28 
    vue-upload-component:  2.8.20 
    vue-yandex-maps:  0.10.9 
    vue2-datepicker:  3.5.0 
    vuedraggable: ^2.24.2 => 2.24.2 (2.24.1)
    vuex: ^3.5.1 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Add dynamic routes to vue-router:
```
const compPath = 'resources/index'
const route = {
        path: routeData.path,
        name: routeName,
        component: () => import(`@/views/${compPath}`),
       ....
}
...
$router.addRoutes([route])
```
And then go to this route - throws error.

Babel config: 
```
 presets: [
    ['@vue/cli-plugin-babel/preset', { useBuiltIns: 'entry' }],
  ],
```

### What is expected?
Dynamic import works normal: resolve path (as: '@/views/resources/index').

### What is actually happening?
After upgrade package "@vue/cli-plugin-babel" to 4.5.7 - does not work: in console writes: 
Unhandled Promise Rejection: Error: Cannot find module '@/views/resources/index'.

---
Packet "@vue/cli-plugin-babel": "<=4.3.1", is working normally.
Packet "@vue/cli-plugin-babel": ">=4.4.0", does not work.

**Comment by sodatea** [comment]
Hi, thanks for your report.
Would you please reduce your issue to [a small reproducible example](https://stackoverflow.com/help/mcve) (e.g. a GitHub repository together with instructions on how to get to the problem)? Without a runnable example it would be difficult for us to find out what is going wrong.

**Comment by sodatea** [comment]
Closing due to inactivity and lack of reproduction.
