### ISSUE TITLE
Support cypress 10 with @vue/cli-plugin-e2e-cypress

### ISSUE THREAD

**Issue by sceee** [vuejs/vue-cli#7195]
### What problem does this feature solve?
After updating cypress to v10 in a project, the following error is logged when executing `vue-cli-service test:e2e --browser chrome --headless`

```
 ERROR  TypeError: runner.on is not a function
TypeError: runner.on is not a function
    at /home/runner/work/my/app/node_modules/@vue/cli-plugin-e2e-cypress/index.js:39:14
```

It seems `@vue/cli-plugin-e2e-cypress` is currently not compatible with cypress 10.
When using cypress v9, it works as expected.

### What does the proposed API look like?
n/a

**Comment by haoqunjiang** [comment]
Fixed in 5.0.5
